services:
  pg:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: corvinvpn
      POSTGRES_PASSWORD: corvinvpn
      POSTGRES_DB: corvinvpn
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: corvinvpn
      MINIO_ROOT_PASSWORD: corvinvpn
    volumes:
      - minio_data:/data
      # - /etc/ssl/corvin-ui:/etc/minio/certs
    command: [ "minio", "server", "/data", "--console-address", ":9001" ]
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - "1765:5671" # AMQP over TLS
      - "11765:15671" # RabbitMQ UI
    environment:
      RABBITMQ_DEFAULT_USER: corvinvpn
      RABBITMQ_DEFAULT_PASS: corvinvpn
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - /etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /etc/ssl/corvin-ui:/etc/rabbitmq/certs
    command: [ "rabbitmq-server" ]
    restart: always
    # networks:
    #   - bot_net

  bot:
    container_name: bot
    image: ghcr.io/dimasmir03/vpnbot:latest
    depends_on:
      - rabbitmq
      - minio
      - pg
    environment:
      - RABBITMQ_URL=amqps://ravenvpn:ravenvpn@rabbitmq:5671/
      - BASE_URL=http://host.docker.internal:8080
    volumes:
      - /etc/ssl/corvin-ui:/app/cert:ro
      - /opt/bot/.env:/app/.env
    restart: always
    # networks:
    #   - bot_net
    network_mode: host
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

volumes:
  rabbitmq_data:
  minio_data:
  pgdata:


networks:
  bot_net:
    driver: bridge
